### ISSUE TITLE
Building on Windows fails with CMake

### ISSUE THREAD

**Issue by IRONIC3D** [kattkieru/tradigitools#1] opened 2021-05-17 00:33 UTC
Hey @kattkieru 

I've been trying to build on windows 10 against Maya 2022 using VSCode but getting a few errors, some I've overcome but one last one is still failing.

To begin with the FindMaya couldn't find Maya even though I've included the variables in the system, I was able to overcome it by setting the variables early on in the file:

```cmake
set(MAYA_INCLUDE_DIR "D:/src/Maya/devkitBase2022/include")
set(MAYA_LIBRARY "D:/src/Maya/devkitBase2022/lib")
#D:/src/Maya/devkitBase2022 is the location of the Maya2022 SDK, prior to setting to the DFK directly I had it pointing to C:/Program Files./Audodesk/Maya2022....etc, it was failing still.
```

When trying to build I get the following error:

```cmake
LINK : fatal error LNK1181: cannot open input file 'D:\src\Maya\devkitBase2022\lib.obj' [D:\src\repos\tradigitools\build\maya\tradigitools.vcxproj]
```

I've tried to play around the folder location, like setting the Maya_LIBRARY to be D:/src/Maya/devkitBase2022/lib/" But the error will end reporting that it cannot find "......./lib/,obj"

Any ideas on how to resolve this issue?

Thank you

**Comment by kattkieru** [comment] 2021-05-17 11:14
Hi there!

This should build without the devkit by specifying the maya2022/lib folder. When I do my pass for Maya 2022 soon I may also convert the setup to use Chad Vernon’s FindMaya machinery.

Have you been able to build for previous versions? Did you get the same error in 2020?

**Comment by IRONIC3D** [comment] 2021-05-18 00:16
No I have the same issue with Maya 2020 and pointing to the actual Maya2020/lib folder directly.

**Comment by IRONIC3D** [comment] 2021-06-09 04:28
Hi @kattkieru

Where you manage to build against 2022 or 2020 on windows?

**Comment by kattkieru** [comment] 2021-06-09 12:17
Hey there. Not yet— in the middle of a move and I haven’t had access to a windows box for testing. I haven’t forgotten! 😉

**Comment by kattkieru** [comment] 2021-06-09 15:37
Hey mate,

Check the releases page-- I made you a build. I'm not seeing the same issue you are on building.

I've updated the README with cmake instructions.  For windows I recommend:

`cmake -G "Visual Studio 16 2019" -DMAYA_VERSION=2022 ..`

for your config build step.  Please note that 2022 requires Visual Studio 2019.

I'm going to close this ticket since I can't reproduce your specific issue, but I hope the binary is good enough for you. :)

**Closed by kattkieru** 2021-06-09 15:37 UTC

**Comment by IRONIC3D** [comment] 2021-06-10 01:08
Awesome mate, its working like a charm in Maya 2022. Thank you for providing the build.

I was using Visual Studio Code to make the build. perhaps I should try with developer command line next time. Thanks for your help.
